/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index";
import * as PTI from "../index";
export declare class UnprocessableEntityError extends errors.PTIError {
    constructor(body: PTI.OneOfAssessmentValidationError);
}
