/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type ComplianceProviderResponseCode = "FRAUD_SUSPICION" | "HIGH_RISK_WALLET" | "TRANSACTION_VELOCITY_VIOLATION" | "GEO_FENCING_VIOLATION" | "BLOCKED_JURISDICTION" | "SANCTION_SCREENING";
export declare const ComplianceProviderResponseCode: {
    readonly FraudSuspicion: "FRAUD_SUSPICION";
    readonly HighRiskWallet: "HIGH_RISK_WALLET";
    readonly TransactionVelocityViolation: "TRANSACTION_VELOCITY_VIOLATION";
    readonly GeoFencingViolation: "GEO_FENCING_VIOLATION";
    readonly BlockedJurisdiction: "BLOCKED_JURISDICTION";
    readonly SanctionScreening: "SANCTION_SCREENING";
};
