"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CurrencyEnum = void 0;
exports.CurrencyEnum = {
    Btc: "BTC",
    Eth: "ETH",
    Sol: "SOL",
    Pol: "POL",
    Usdc: "USDC",
    Usd: "USD",
    Trx: "TRX",
    Ltc: "LTC",
    Ada: "ADA",
    Xrp: "XRP",
    Xlm: "XLM",
    Doge: "DOGE",
    Ton: "TON",
    Avax: "AVAX",
    Hbar: "HBAR",
};
