/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type CurrencyType = "CRYPTO" | "FIAT";
export declare const CurrencyType: {
    readonly Crypto: "CRYPTO";
    readonly Fiat: "FIAT";
};
