/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type DeviceProviderName = "SARDINE" | "UNKNOWN";
export declare const DeviceProviderName: {
    readonly Sardine: "SARDINE";
    readonly Unknown: "UNKNOWN";
};
