/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type DigitalItemType = "NFT" | "OTHER";
export declare const DigitalItemType: {
    readonly Nft: "NFT";
    readonly Other: "OTHER";
};
