/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type ErrorType = "INVALID_REQUEST" | "MIN_INFO_MISSING" | "MIN_ASSESSMENT_MISSING" | "ALREADY_IN_PROGRESS" | "NO_ERROR" | "MISSING_WALLET" | "WALLETS_DIFFERENT_CURRENCY" | "WALLETS_SAME_CURRENCY" | "SOURCE_WALLET_DESTINATION_TOKEN_ONLY" | "ITEM_USD_VALUE_REQUIRED_WHEN_MULTIPLE_ITEMS" | "INVALID_USER_TAG" | "MISSING_TRANSACTION_GROUP_ID" | "DIFFERENT_BUY_SELL_AMOUNT" | "DIFFERENT_BUY_SELL_CURRENCIES" | "NO_INTER_CLIENTS_TRANSFERS" | "CLIENT_CONFIGURATION_ERROR" | "UNSUPPORTED_OPERATION" | "COUNTRY_NOT_SUPPORTED" | "NOT_ENOUGH_FUNDS" | "INVALID_ASSET_OWNERSHIP" | "FEES_WALLET_NOT_FOUND" | "REVERT_ONLY_CHARGE_BACK" | "MISSING_CORRESPONDING_BUY_TRANSACTION" | "ALREADY_EXISTING_CORRESPONDING_TRANSACTION_PAIR" | "BUY_TRANSACTION_NOT_SETTLED" | "FIAT_ONLY" | "SOURCE_DESTINATION_WALLET" | "INVALID_SOURCE_CURRENCY" | "INVALID_DESTINATION_CURRENCY" | "USD_WALLET_ONLY" | "BANK_ONLY" | "MISSING_EMAIL_ADDRESS" | "MISSING_BANK_ACCOUNT_INFORMATION" | "MISSING_BANK_ACCOUNT_NUMBER_INFORMATION" | "MISSING_BANK_ACCOUNT_TYPE" | "MANDATORY_IP_ADDRESS" | "MANDATORY_EMAIL_ADDRESS" | "MISSING_CC_INFO" | "CC_ONLY" | "UNABLE_TO_PROVIDE_ESTIMATES" | "FUNDING_FROM_CRYPTO_ONLY" | "WITHDRAWAL_FROM_WALLET_TO_CRYPTO" | "SOURCE_WALLET_CURRENCY_DIFFERENT_THAN_DESTINATION_TOKEN_CURRENCY";
export declare const ErrorType: {
    readonly InvalidRequest: "INVALID_REQUEST";
    readonly MinInfoMissing: "MIN_INFO_MISSING";
    readonly MinAssessmentMissing: "MIN_ASSESSMENT_MISSING";
    readonly AlreadyInProgress: "ALREADY_IN_PROGRESS";
    readonly NoError: "NO_ERROR";
    readonly MissingWallet: "MISSING_WALLET";
    readonly WalletsDifferentCurrency: "WALLETS_DIFFERENT_CURRENCY";
    readonly WalletsSameCurrency: "WALLETS_SAME_CURRENCY";
    readonly SourceWalletDestinationTokenOnly: "SOURCE_WALLET_DESTINATION_TOKEN_ONLY";
    readonly ItemUsdValueRequiredWhenMultipleItems: "ITEM_USD_VALUE_REQUIRED_WHEN_MULTIPLE_ITEMS";
    readonly InvalidUserTag: "INVALID_USER_TAG";
    readonly MissingTransactionGroupId: "MISSING_TRANSACTION_GROUP_ID";
    readonly DifferentBuySellAmount: "DIFFERENT_BUY_SELL_AMOUNT";
    readonly DifferentBuySellCurrencies: "DIFFERENT_BUY_SELL_CURRENCIES";
    readonly NoInterClientsTransfers: "NO_INTER_CLIENTS_TRANSFERS";
    readonly ClientConfigurationError: "CLIENT_CONFIGURATION_ERROR";
    readonly UnsupportedOperation: "UNSUPPORTED_OPERATION";
    readonly CountryNotSupported: "COUNTRY_NOT_SUPPORTED";
    readonly NotEnoughFunds: "NOT_ENOUGH_FUNDS";
    readonly InvalidAssetOwnership: "INVALID_ASSET_OWNERSHIP";
    readonly FeesWalletNotFound: "FEES_WALLET_NOT_FOUND";
    readonly RevertOnlyChargeBack: "REVERT_ONLY_CHARGE_BACK";
    readonly MissingCorrespondingBuyTransaction: "MISSING_CORRESPONDING_BUY_TRANSACTION";
    readonly AlreadyExistingCorrespondingTransactionPair: "ALREADY_EXISTING_CORRESPONDING_TRANSACTION_PAIR";
    readonly BuyTransactionNotSettled: "BUY_TRANSACTION_NOT_SETTLED";
    readonly FiatOnly: "FIAT_ONLY";
    readonly SourceDestinationWallet: "SOURCE_DESTINATION_WALLET";
    readonly InvalidSourceCurrency: "INVALID_SOURCE_CURRENCY";
    readonly InvalidDestinationCurrency: "INVALID_DESTINATION_CURRENCY";
    readonly UsdWalletOnly: "USD_WALLET_ONLY";
    readonly BankOnly: "BANK_ONLY";
    readonly MissingEmailAddress: "MISSING_EMAIL_ADDRESS";
    readonly MissingBankAccountInformation: "MISSING_BANK_ACCOUNT_INFORMATION";
    readonly MissingBankAccountNumberInformation: "MISSING_BANK_ACCOUNT_NUMBER_INFORMATION";
    readonly MissingBankAccountType: "MISSING_BANK_ACCOUNT_TYPE";
    readonly MandatoryIpAddress: "MANDATORY_IP_ADDRESS";
    readonly MandatoryEmailAddress: "MANDATORY_EMAIL_ADDRESS";
    readonly MissingCcInfo: "MISSING_CC_INFO";
    readonly CcOnly: "CC_ONLY";
    readonly UnableToProvideEstimates: "UNABLE_TO_PROVIDE_ESTIMATES";
    readonly FundingFromCryptoOnly: "FUNDING_FROM_CRYPTO_ONLY";
    readonly WithdrawalFromWalletToCrypto: "WITHDRAWAL_FROM_WALLET_TO_CRYPTO";
    readonly SourceWalletCurrencyDifferentThanDestinationTokenCurrency: "SOURCE_WALLET_CURRENCY_DIFFERENT_THAN_DESTINATION_TOKEN_CURRENCY";
};
