/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PTI from "../index";
export type KycRequest = PTI.KycRequest.Person | PTI.KycRequest.Business;
export declare namespace KycRequest {
    interface Person extends PTI.PersonKycRequest {
        type: "PERSON";
    }
    interface Business extends PTI.BusinessKycRequest {
        type: "BUSINESS";
    }
}
