/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type TransactionAssessStatus = "PENDING" | "ERROR" | "MANUAL_REVIEW" | "PROCEED" | "STOP";
export declare const TransactionAssessStatus: {
    readonly Pending: "PENDING";
    readonly Error: "ERROR";
    readonly ManualReview: "MANUAL_REVIEW";
    readonly Proceed: "PROCEED";
    readonly Stop: "STOP";
};
