/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const TransactionTypeEnum = {
    Deposit: "DEPOSIT",
    Withdrawal: "WITHDRAWAL",
    Payment: "PAYMENT",
    Transfer: "TRANSFER",
    Sell: "SELL",
    Buy: "BUY",
    Mint: "MINT",
    Trade: "TRADE",
};
