/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PTI from "../index";
/**
 * Status of a transaction assessment request. The date property is the date that the reported transaction occurred.
 */
export interface TransactionAssessStatusObject extends PTI.ActionStatus {
    assessment?: PTI.TransactionAssessStatus;
    risk?: PTI.TransactionRiskAssessment;
    amount?: number;
    transactionType?: PTI.TransactionTypeEnum;
    transactionGroupId?: PTI.UuidLikeStrTransactionGroup;
    /** key/value map of extra information */
    meta?: Record<string, unknown>;
    transactionMonitoringResultDetail?: PTI.TransactionAssessStatusObjectTransactionMonitoringResultDetail;
}
