/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type UserAssessStatus = "PENDING" | "ERROR" | "UNDER_REVIEW" | "REQUESTED_MORE_INFORMATION" | "ACCEPTED" | "REFUSED" | "INVALID";
export declare const UserAssessStatus: {
    readonly Pending: "PENDING";
    readonly Error: "ERROR";
    readonly UnderReview: "UNDER_REVIEW";
    readonly RequestedMoreInformation: "REQUESTED_MORE_INFORMATION";
    readonly Accepted: "ACCEPTED";
    readonly Refused: "REFUSED";
    readonly Invalid: "INVALID";
};
