/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type WalletHistoryOperationTarget = "LOCKED_BALANCE" | "PENDING_BALANCE" | "TOTAL_BALANCE";
export declare const WalletHistoryOperationTarget: {
    readonly LockedBalance: "LOCKED_BALANCE";
    readonly PendingBalance: "PENDING_BALANCE";
    readonly TotalBalance: "TOTAL_BALANCE";
};
