/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const WalletHistoryOperationTarget = {
    LockedBalance: "LOCKED_BALANCE",
    PendingBalance: "PENDING_BALANCE",
    TotalBalance: "TOTAL_BALANCE",
};
