/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
import { DigitalItem } from "../../../../types/DigitalItem";
import { OneOfPaymentMethod } from "../../../../types/OneOfPaymentMethod";
import { OneOfUserSubTypes } from "../../../../types/OneOfUserSubTypes";
import { FeeRecipient } from "../../../../types/FeeRecipient";
import { TransactionType } from "../../../../types/TransactionType";
export const ExecuteSellTransaction = core.serialization
    .object({
    digitalItem: DigitalItem.optional(),
    digitalItems: core.serialization.list(DigitalItem).optional(),
    destinationMethod: OneOfPaymentMethod,
    buyer: OneOfUserSubTypes.optional(),
    feeRecipients: core.serialization.list(FeeRecipient).optional(),
})
    .extend(TransactionType);
