/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as PTI from "../../../../../api/index";
import * as core from "../../../../../core";
import { WalletPaymentMethodWrapper } from "../../../../types/WalletPaymentMethodWrapper";
import { TransactionType } from "../../../../types/TransactionType";
export declare const ExecuteUnstakeTransaction: core.serialization.Schema<serializers.ExecuteUnstakeTransaction.Raw, Omit<PTI.ExecuteUnstakeTransaction, "ptiRequestId" | "ptiScenarioId" | "ptiSessionId" | "ptiDisableWebhook" | "ptiProviderName">>;
export declare namespace ExecuteUnstakeTransaction {
    interface Raw extends TransactionType.Raw {
        sourceMethod: WalletPaymentMethodWrapper.Raw;
    }
}
