/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
import { OneOfExternalPaymentMethod } from "../../../../types/OneOfExternalPaymentMethod";
import { WalletPaymentMethod } from "../../../../types/WalletPaymentMethod";
import { TransactionType } from "../../../../types/TransactionType";
export const ExecuteDepositTransaction = core.serialization
    .object({
    sourceMethod: OneOfExternalPaymentMethod,
    destinationMethod: WalletPaymentMethod.optional(),
})
    .extend(TransactionType);
