/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
import { TransactionUpdateProviderName } from "../../types/TransactionUpdateProviderName";
import { TransactionUpdateFeedback } from "../../types/TransactionUpdateFeedback";
export const TransactionUpdate = core.serialization.object({
    payload: core.serialization.string().optional(),
    providerName: TransactionUpdateProviderName,
    feedback: TransactionUpdateFeedback,
    transactionId: core.serialization.string().optional(),
    date: core.serialization.string().optional(),
});
