/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum BankAccountPaymentInformationBankAccountType {
  CHECKING("CHECKING"),

  SAVINGS("SAVINGS");

  private final String value;

  BankAccountPaymentInformationBankAccountType(String value) {
    this.value = value;
  }

  @JsonValue
  @Override
  public String toString() {
    return this.value;
  }
}
