/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum CurrencyEnum {
  BTC("BTC"),

  ETH("ETH"),

  SOL("SOL"),

  POL("POL"),

  USDC("USDC"),

  USD("USD"),

  TRX("TRX"),

  LTC("LTC"),

  ADA("ADA"),

  XRP("XRP"),

  XLM("XLM"),

  DOGE("DOGE"),

  TON("TON"),

  AVAX("AVAX"),

  HBAR("HBAR");

  private final String value;

  CurrencyEnum(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
