/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum CurrencyEnum {
  BTC("BTC"),

  ETH("ETH"),

  SOL("SOL"),

  POL("POL"),

  USDC("USDC"),

  USD("USD");

  private final String value;

  CurrencyEnum(String value) {
    this.value = value;
  }

  @JsonValue
  @Override
  public String toString() {
    return this.value;
  }
}
