/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum PaymentInformationType {
  BANK_ACCOUNT("BANK_ACCOUNT"),

  ENCRYPTED_CREDIT_CARD("ENCRYPTED_CREDIT_CARD"),

  TOKEN("TOKEN"),

  WALLET("WALLET");

  private final String value;

  PaymentInformationType(String value) {
    this.value = value;
  }

  @JsonValue
  @Override
  public String toString() {
    return this.value;
  }
}
