/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pti.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Person.Builder.class
)
public final class Person implements IUser {
  private final String id;

  private final Optional<UserStatus> status;

  private final Optional<UserStatusReason> statusReason;

  private final Optional<List<String>> tags;

  private final Optional<List<OneOfExternalPaymentInformation>> paymentInformation;

  private final Optional<String> sourceOfFunds;

  private final Optional<String> userCreationDate;

  private final Optional<Map<String, Object>> userPtiMeta;

  private final Optional<Map<String, Object>> userClientMeta;

  private final Optional<List<Address>> addresses;

  private final Optional<List<OneOfPiiSubTypes>> piis;

  private final Optional<List<Email>> emails;

  private final Optional<List<Device>> devices;

  private final Optional<List<Phone>> phones;

  private final Optional<Name> name;

  private final Optional<String> gender;

  private final Optional<String> dateOfBirth;

  private final Optional<String> countryOfCitizenship;

  private final Map<String, Object> additionalProperties;

  private Person(String id, Optional<UserStatus> status, Optional<UserStatusReason> statusReason,
      Optional<List<String>> tags,
      Optional<List<OneOfExternalPaymentInformation>> paymentInformation,
      Optional<String> sourceOfFunds, Optional<String> userCreationDate,
      Optional<Map<String, Object>> userPtiMeta, Optional<Map<String, Object>> userClientMeta,
      Optional<List<Address>> addresses, Optional<List<OneOfPiiSubTypes>> piis,
      Optional<List<Email>> emails, Optional<List<Device>> devices, Optional<List<Phone>> phones,
      Optional<Name> name, Optional<String> gender, Optional<String> dateOfBirth,
      Optional<String> countryOfCitizenship, Map<String, Object> additionalProperties) {
    this.id = id;
    this.status = status;
    this.statusReason = statusReason;
    this.tags = tags;
    this.paymentInformation = paymentInformation;
    this.sourceOfFunds = sourceOfFunds;
    this.userCreationDate = userCreationDate;
    this.userPtiMeta = userPtiMeta;
    this.userClientMeta = userClientMeta;
    this.addresses = addresses;
    this.piis = piis;
    this.emails = emails;
    this.devices = devices;
    this.phones = phones;
    this.name = name;
    this.gender = gender;
    this.dateOfBirth = dateOfBirth;
    this.countryOfCitizenship = countryOfCitizenship;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Unique identifier for this User. This value MUST be chosen and stored at User creation time.
   */
  @JsonProperty("id")
  @Override
  public String getId() {
    return id;
  }

  @JsonProperty("status")
  @Override
  public Optional<UserStatus> getStatus() {
    return status;
  }

  @JsonProperty("statusReason")
  @Override
  public Optional<UserStatusReason> getStatusReason() {
    return statusReason;
  }

  /**
   * @return Tag that characterizes the User. Used for internal classification purposes.
   */
  @JsonProperty("tags")
  @Override
  public Optional<List<String>> getTags() {
    return tags;
  }

  @JsonProperty("paymentInformation")
  @Override
  public Optional<List<OneOfExternalPaymentInformation>> getPaymentInformation() {
    return paymentInformation;
  }

  @JsonProperty("sourceOfFunds")
  @Override
  public Optional<String> getSourceOfFunds() {
    return sourceOfFunds;
  }

  /**
   * @return Optional ISO-8601 value. Used to provide the date the User was created in your system. If left empty, it will be populated at current time.
   */
  @JsonProperty("userCreationDate")
  @Override
  public Optional<String> getUserCreationDate() {
    return userCreationDate;
  }

  /**
   * @return key/value map of extra meta data for this request (used by PTI)
   */
  @JsonProperty("userPtiMeta")
  @Override
  public Optional<Map<String, Object>> getUserPtiMeta() {
    return userPtiMeta;
  }

  /**
   * @return key/value map of extra meta data for this request (used by Client)
   */
  @JsonProperty("userClientMeta")
  @Override
  public Optional<Map<String, Object>> getUserClientMeta() {
    return userClientMeta;
  }

  @JsonProperty("addresses")
  public Optional<List<Address>> getAddresses() {
    return addresses;
  }

  @JsonProperty("piis")
  public Optional<List<OneOfPiiSubTypes>> getPiis() {
    return piis;
  }

  @JsonProperty("emails")
  public Optional<List<Email>> getEmails() {
    return emails;
  }

  @JsonProperty("devices")
  public Optional<List<Device>> getDevices() {
    return devices;
  }

  @JsonProperty("phones")
  public Optional<List<Phone>> getPhones() {
    return phones;
  }

  @JsonProperty("name")
  public Optional<Name> getName() {
    return name;
  }

  /**
   * @return ISO/IEC 5218 / vCard4
   */
  @JsonProperty("gender")
  public Optional<String> getGender() {
    return gender;
  }

  /**
   * @return ISO 8601
   */
  @JsonProperty("dateOfBirth")
  public Optional<String> getDateOfBirth() {
    return dateOfBirth;
  }

  /**
   * @return Comma separated list of ISO 3166 alpha 1 country codes
   */
  @JsonProperty("countryOfCitizenship")
  public Optional<String> getCountryOfCitizenship() {
    return countryOfCitizenship;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Person && equalTo((Person) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Person other) {
    return id.equals(other.id) && status.equals(other.status) && statusReason.equals(other.statusReason) && tags.equals(other.tags) && paymentInformation.equals(other.paymentInformation) && sourceOfFunds.equals(other.sourceOfFunds) && userCreationDate.equals(other.userCreationDate) && userPtiMeta.equals(other.userPtiMeta) && userClientMeta.equals(other.userClientMeta) && addresses.equals(other.addresses) && piis.equals(other.piis) && emails.equals(other.emails) && devices.equals(other.devices) && phones.equals(other.phones) && name.equals(other.name) && gender.equals(other.gender) && dateOfBirth.equals(other.dateOfBirth) && countryOfCitizenship.equals(other.countryOfCitizenship);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.id, this.status, this.statusReason, this.tags, this.paymentInformation, this.sourceOfFunds, this.userCreationDate, this.userPtiMeta, this.userClientMeta, this.addresses, this.piis, this.emails, this.devices, this.phones, this.name, this.gender, this.dateOfBirth, this.countryOfCitizenship);
  }

  @Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    _FinalStage id(@NotNull String id);

    Builder from(Person other);
  }

  public interface _FinalStage {
    Person build();

    _FinalStage status(Optional<UserStatus> status);

    _FinalStage status(UserStatus status);

    _FinalStage statusReason(Optional<UserStatusReason> statusReason);

    _FinalStage statusReason(UserStatusReason statusReason);

    _FinalStage tags(Optional<List<String>> tags);

    _FinalStage tags(List<String> tags);

    _FinalStage paymentInformation(
        Optional<List<OneOfExternalPaymentInformation>> paymentInformation);

    _FinalStage paymentInformation(List<OneOfExternalPaymentInformation> paymentInformation);

    _FinalStage sourceOfFunds(Optional<String> sourceOfFunds);

    _FinalStage sourceOfFunds(String sourceOfFunds);

    _FinalStage userCreationDate(Optional<String> userCreationDate);

    _FinalStage userCreationDate(String userCreationDate);

    _FinalStage userPtiMeta(Optional<Map<String, Object>> userPtiMeta);

    _FinalStage userPtiMeta(Map<String, Object> userPtiMeta);

    _FinalStage userClientMeta(Optional<Map<String, Object>> userClientMeta);

    _FinalStage userClientMeta(Map<String, Object> userClientMeta);

    _FinalStage addresses(Optional<List<Address>> addresses);

    _FinalStage addresses(List<Address> addresses);

    _FinalStage piis(Optional<List<OneOfPiiSubTypes>> piis);

    _FinalStage piis(List<OneOfPiiSubTypes> piis);

    _FinalStage emails(Optional<List<Email>> emails);

    _FinalStage emails(List<Email> emails);

    _FinalStage devices(Optional<List<Device>> devices);

    _FinalStage devices(List<Device> devices);

    _FinalStage phones(Optional<List<Phone>> phones);

    _FinalStage phones(List<Phone> phones);

    _FinalStage name(Optional<Name> name);

    _FinalStage name(Name name);

    _FinalStage gender(Optional<String> gender);

    _FinalStage gender(String gender);

    _FinalStage dateOfBirth(Optional<String> dateOfBirth);

    _FinalStage dateOfBirth(String dateOfBirth);

    _FinalStage countryOfCitizenship(Optional<String> countryOfCitizenship);

    _FinalStage countryOfCitizenship(String countryOfCitizenship);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, _FinalStage {
    private String id;

    private Optional<String> countryOfCitizenship = Optional.empty();

    private Optional<String> dateOfBirth = Optional.empty();

    private Optional<String> gender = Optional.empty();

    private Optional<Name> name = Optional.empty();

    private Optional<List<Phone>> phones = Optional.empty();

    private Optional<List<Device>> devices = Optional.empty();

    private Optional<List<Email>> emails = Optional.empty();

    private Optional<List<OneOfPiiSubTypes>> piis = Optional.empty();

    private Optional<List<Address>> addresses = Optional.empty();

    private Optional<Map<String, Object>> userClientMeta = Optional.empty();

    private Optional<Map<String, Object>> userPtiMeta = Optional.empty();

    private Optional<String> userCreationDate = Optional.empty();

    private Optional<String> sourceOfFunds = Optional.empty();

    private Optional<List<OneOfExternalPaymentInformation>> paymentInformation = Optional.empty();

    private Optional<List<String>> tags = Optional.empty();

    private Optional<UserStatusReason> statusReason = Optional.empty();

    private Optional<UserStatus> status = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @Override
    public Builder from(Person other) {
      id(other.getId());
      status(other.getStatus());
      statusReason(other.getStatusReason());
      tags(other.getTags());
      paymentInformation(other.getPaymentInformation());
      sourceOfFunds(other.getSourceOfFunds());
      userCreationDate(other.getUserCreationDate());
      userPtiMeta(other.getUserPtiMeta());
      userClientMeta(other.getUserClientMeta());
      addresses(other.getAddresses());
      piis(other.getPiis());
      emails(other.getEmails());
      devices(other.getDevices());
      phones(other.getPhones());
      name(other.getName());
      gender(other.getGender());
      dateOfBirth(other.getDateOfBirth());
      countryOfCitizenship(other.getCountryOfCitizenship());
      return this;
    }

    /**
     * <p>Unique identifier for this User. This value MUST be chosen and stored at User creation time.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    @JsonSetter("id")
    public _FinalStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>Comma separated list of ISO 3166 alpha 1 country codes</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage countryOfCitizenship(String countryOfCitizenship) {
      this.countryOfCitizenship = Optional.ofNullable(countryOfCitizenship);
      return this;
    }

    @Override
    @JsonSetter(
        value = "countryOfCitizenship",
        nulls = Nulls.SKIP
    )
    public _FinalStage countryOfCitizenship(Optional<String> countryOfCitizenship) {
      this.countryOfCitizenship = countryOfCitizenship;
      return this;
    }

    /**
     * <p>ISO 8601</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage dateOfBirth(String dateOfBirth) {
      this.dateOfBirth = Optional.ofNullable(dateOfBirth);
      return this;
    }

    @Override
    @JsonSetter(
        value = "dateOfBirth",
        nulls = Nulls.SKIP
    )
    public _FinalStage dateOfBirth(Optional<String> dateOfBirth) {
      this.dateOfBirth = dateOfBirth;
      return this;
    }

    /**
     * <p>ISO/IEC 5218 / vCard4</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage gender(String gender) {
      this.gender = Optional.ofNullable(gender);
      return this;
    }

    @Override
    @JsonSetter(
        value = "gender",
        nulls = Nulls.SKIP
    )
    public _FinalStage gender(Optional<String> gender) {
      this.gender = gender;
      return this;
    }

    @Override
    public _FinalStage name(Name name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<Name> name) {
      this.name = name;
      return this;
    }

    @Override
    public _FinalStage phones(List<Phone> phones) {
      this.phones = Optional.ofNullable(phones);
      return this;
    }

    @Override
    @JsonSetter(
        value = "phones",
        nulls = Nulls.SKIP
    )
    public _FinalStage phones(Optional<List<Phone>> phones) {
      this.phones = phones;
      return this;
    }

    @Override
    public _FinalStage devices(List<Device> devices) {
      this.devices = Optional.ofNullable(devices);
      return this;
    }

    @Override
    @JsonSetter(
        value = "devices",
        nulls = Nulls.SKIP
    )
    public _FinalStage devices(Optional<List<Device>> devices) {
      this.devices = devices;
      return this;
    }

    @Override
    public _FinalStage emails(List<Email> emails) {
      this.emails = Optional.ofNullable(emails);
      return this;
    }

    @Override
    @JsonSetter(
        value = "emails",
        nulls = Nulls.SKIP
    )
    public _FinalStage emails(Optional<List<Email>> emails) {
      this.emails = emails;
      return this;
    }

    @Override
    public _FinalStage piis(List<OneOfPiiSubTypes> piis) {
      this.piis = Optional.ofNullable(piis);
      return this;
    }

    @Override
    @JsonSetter(
        value = "piis",
        nulls = Nulls.SKIP
    )
    public _FinalStage piis(Optional<List<OneOfPiiSubTypes>> piis) {
      this.piis = piis;
      return this;
    }

    @Override
    public _FinalStage addresses(List<Address> addresses) {
      this.addresses = Optional.ofNullable(addresses);
      return this;
    }

    @Override
    @JsonSetter(
        value = "addresses",
        nulls = Nulls.SKIP
    )
    public _FinalStage addresses(Optional<List<Address>> addresses) {
      this.addresses = addresses;
      return this;
    }

    /**
     * <p>key/value map of extra meta data for this request (used by Client)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage userClientMeta(Map<String, Object> userClientMeta) {
      this.userClientMeta = Optional.ofNullable(userClientMeta);
      return this;
    }

    @Override
    @JsonSetter(
        value = "userClientMeta",
        nulls = Nulls.SKIP
    )
    public _FinalStage userClientMeta(Optional<Map<String, Object>> userClientMeta) {
      this.userClientMeta = userClientMeta;
      return this;
    }

    /**
     * <p>key/value map of extra meta data for this request (used by PTI)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage userPtiMeta(Map<String, Object> userPtiMeta) {
      this.userPtiMeta = Optional.ofNullable(userPtiMeta);
      return this;
    }

    @Override
    @JsonSetter(
        value = "userPtiMeta",
        nulls = Nulls.SKIP
    )
    public _FinalStage userPtiMeta(Optional<Map<String, Object>> userPtiMeta) {
      this.userPtiMeta = userPtiMeta;
      return this;
    }

    /**
     * <p>Optional ISO-8601 value. Used to provide the date the User was created in your system. If left empty, it will be populated at current time.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage userCreationDate(String userCreationDate) {
      this.userCreationDate = Optional.ofNullable(userCreationDate);
      return this;
    }

    @Override
    @JsonSetter(
        value = "userCreationDate",
        nulls = Nulls.SKIP
    )
    public _FinalStage userCreationDate(Optional<String> userCreationDate) {
      this.userCreationDate = userCreationDate;
      return this;
    }

    @Override
    public _FinalStage sourceOfFunds(String sourceOfFunds) {
      this.sourceOfFunds = Optional.ofNullable(sourceOfFunds);
      return this;
    }

    @Override
    @JsonSetter(
        value = "sourceOfFunds",
        nulls = Nulls.SKIP
    )
    public _FinalStage sourceOfFunds(Optional<String> sourceOfFunds) {
      this.sourceOfFunds = sourceOfFunds;
      return this;
    }

    @Override
    public _FinalStage paymentInformation(
        List<OneOfExternalPaymentInformation> paymentInformation) {
      this.paymentInformation = Optional.ofNullable(paymentInformation);
      return this;
    }

    @Override
    @JsonSetter(
        value = "paymentInformation",
        nulls = Nulls.SKIP
    )
    public _FinalStage paymentInformation(
        Optional<List<OneOfExternalPaymentInformation>> paymentInformation) {
      this.paymentInformation = paymentInformation;
      return this;
    }

    /**
     * <p>Tag that characterizes the User. Used for internal classification purposes.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @Override
    public _FinalStage tags(List<String> tags) {
      this.tags = Optional.ofNullable(tags);
      return this;
    }

    @Override
    @JsonSetter(
        value = "tags",
        nulls = Nulls.SKIP
    )
    public _FinalStage tags(Optional<List<String>> tags) {
      this.tags = tags;
      return this;
    }

    @Override
    public _FinalStage statusReason(UserStatusReason statusReason) {
      this.statusReason = Optional.ofNullable(statusReason);
      return this;
    }

    @Override
    @JsonSetter(
        value = "statusReason",
        nulls = Nulls.SKIP
    )
    public _FinalStage statusReason(Optional<UserStatusReason> statusReason) {
      this.statusReason = statusReason;
      return this;
    }

    @Override
    public _FinalStage status(UserStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @Override
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public _FinalStage status(Optional<UserStatus> status) {
      this.status = status;
      return this;
    }

    @Override
    public Person build() {
      return new Person(id, status, statusReason, tags, paymentInformation, sourceOfFunds, userCreationDate, userPtiMeta, userClientMeta, addresses, piis, emails, devices, phones, name, gender, dateOfBirth, countryOfCitizenship, additionalProperties);
    }
  }
}
