/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum ResourceType {
  USER_ASSESSMENT("USER_ASSESSMENT"),

  TRANSACTION_ASSESSMENT("TRANSACTION_ASSESSMENT"),

  TRANSACTION_STATUS("TRANSACTION_STATUS"),

  USER_UPDATE("USER_UPDATE"),

  TRANSACTION_QUOTE_UPDATE("TRANSACTION_QUOTE_UPDATE");

  private final String value;

  ResourceType(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
