/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pti.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StateCode.Builder.class
)
public final class StateCode {
  private final Optional<String> code;

  private final Map<String, Object> additionalProperties;

  private StateCode(Optional<String> code, Map<String, Object> additionalProperties) {
    this.code = code;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return ISO 3166-2 state code, example US-CA
   */
  @JsonProperty("code")
  public Optional<String> getCode() {
    return code;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StateCode && equalTo((StateCode) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StateCode other) {
    return code.equals(other.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.code);
  }

  @Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> code = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(StateCode other) {
      code(other.getCode());
      return this;
    }

    @JsonSetter(
        value = "code",
        nulls = Nulls.SKIP
    )
    public Builder code(Optional<String> code) {
      this.code = code;
      return this;
    }

    public Builder code(String code) {
      this.code = Optional.ofNullable(code);
      return this;
    }

    public StateCode build() {
      return new StateCode(code, additionalProperties);
    }
  }
}
