/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum TransactionRiskAssessment {
  LOW("LOW"),

  MEDIUM("MEDIUM"),

  HIGH("HIGH");

  private final String value;

  TransactionRiskAssessment(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
