/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.pti.sdk.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum TransactionStatus {
  PENDING("PENDING"),

  ERROR("ERROR"),

  MANUAL_REVIEW("MANUAL_REVIEW"),

  REFUSED("REFUSED"),

  AWAITING_PAYMENT("AWAITING_PAYMENT"),

  AUTHORIZED("AUTHORIZED"),

  ACCEPTED("ACCEPTED"),

  BAD_REQUEST("BAD_REQUEST"),

  SETTLED("SETTLED"),

  CAPTURED("CAPTURED"),

  CHARGED_BACK("CHARGED_BACK"),

  CHARGED_BACK_REVERSED("CHARGED_BACK_REVERSED"),

  CANCELED("CANCELED"),

  REFUNDED("REFUNDED");

  private final String value;

  TransactionStatus(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
