/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { BankAccountPaymentInformationBankAccountType } from "./BankAccountPaymentInformationBankAccountType";
import { ExternalPaymentInformation } from "./ExternalPaymentInformation";
export const BankAccountPaymentInformation = core.serialization
    .object({
    bankAccountNumber: core.serialization.string().optional(),
    bankAccountType: BankAccountPaymentInformationBankAccountType.optional(),
    accountHolderName: core.serialization.string().optional(),
    bankSwiftCode: core.serialization.string().optional(),
    bankRoutingNumber: core.serialization.string().optional(),
    bankRoutingCheckDigit: core.serialization.string().optional(),
    accountBankName: core.serialization.string().optional(),
})
    .extend(ExternalPaymentInformation);
