/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
import { OneOfBiiSubTypes } from "./OneOfBiiSubTypes";
import { Address } from "./Address";
import { Email } from "./Email";
import { BusinessOwner } from "./BusinessOwner";
import { Phone } from "./Phone";
import { User } from "./User";
export declare const Business: core.serialization.ObjectSchema<serializers.Business.Raw, PTI.Business>;
export declare namespace Business {
    interface Raw extends User.Raw {
        biis?: OneOfBiiSubTypes.Raw[] | null;
        addresses?: Address.Raw[] | null;
        emails?: Email.Raw[] | null;
        mainRepresentative: BusinessOwner.Raw;
        coOwners?: BusinessOwner.Raw[] | null;
        phones?: Phone.Raw[] | null;
        sectors?: string[] | null;
        creationDate?: string | null;
        businessType?: string | null;
        businessName?: string | null;
        coutryOfIncorporation?: string | null;
    }
}
