/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
import { OneOfPaymentMethod } from "./OneOfPaymentMethod";
import { DigitalItem } from "./DigitalItem";
import { OneOfUserSubTypes } from "./OneOfUserSubTypes";
import { TransactionType } from "./TransactionType";
export declare const BuyTransaction: core.serialization.ObjectSchema<serializers.BuyTransaction.Raw, PTI.BuyTransaction>;
export declare namespace BuyTransaction {
    interface Raw extends TransactionType.Raw {
        sourceMethod?: OneOfPaymentMethod.Raw | null;
        destinationMethod?: OneOfPaymentMethod.Raw | null;
        digitalItem?: DigitalItem.Raw | null;
        seller?: OneOfUserSubTypes.Raw | null;
    }
}
