/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const CurrencyEnum = core.serialization.enum_(["BTC", "ETH", "SOL", "POL", "USDC", "USD", "TRX", "LTC", "ADA"]);
