/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
export declare const FeeRecipientFeeRecipientType: core.serialization.Schema<serializers.FeeRecipientFeeRecipientType.Raw, PTI.FeeRecipientFeeRecipientType>;
export declare namespace FeeRecipientFeeRecipientType {
    type Raw = "COMMISSION" | "BUSINESS";
}
