/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { ObjectReference } from "./ObjectReference";
export const ObjectReferencePage = core.serialization.object({
    page: core.serialization.number().optional(),
    pageSize: core.serialization.number().optional(),
    total: core.serialization.number().optional(),
    items: core.serialization.list(ObjectReference).optional(),
});
