/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
import { AchPaymentMethod } from "./AchPaymentMethod";
import { CreditCardPaymentMethod } from "./CreditCardPaymentMethod";
import { WirePaymentMethod } from "./WirePaymentMethod";
import { WalletPaymentMethod } from "./WalletPaymentMethod";
import { CryptoPaymentMethod } from "./CryptoPaymentMethod";
export declare const OneOfPaymentMethod: core.serialization.Schema<serializers.OneOfPaymentMethod.Raw, PTI.OneOfPaymentMethod>;
export declare namespace OneOfPaymentMethod {
    type Raw = OneOfPaymentMethod.Ach | OneOfPaymentMethod.CreditCard | OneOfPaymentMethod.Wire | OneOfPaymentMethod.Wallet | OneOfPaymentMethod.Crypto;
    interface Ach extends AchPaymentMethod.Raw {
        paymentMethodType: "ACH";
    }
    interface CreditCard extends CreditCardPaymentMethod.Raw {
        paymentMethodType: "CREDIT_CARD";
    }
    interface Wire extends WirePaymentMethod.Raw {
        paymentMethodType: "WIRE";
    }
    interface Wallet extends WalletPaymentMethod.Raw {
        paymentMethodType: "WALLET";
    }
    interface Crypto extends CryptoPaymentMethod.Raw {
        paymentMethodType: "CRYPTO";
    }
}
