/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { MissingInformationError } from "./MissingInformationError";
import { InvalidUserAssessmentError } from "./InvalidUserAssessmentError";
import { NoAssessmentError } from "./NoAssessmentError";
export const OneOfAssessmentValidationError = core.serialization.undiscriminatedUnion([MissingInformationError, InvalidUserAssessmentError, NoAssessmentError]);
