/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
export declare const Pageable: core.serialization.ObjectSchema<serializers.Pageable.Raw, PTI.Pageable>;
export declare namespace Pageable {
    interface Raw {
        pageNumber?: number | null;
        pageSize?: number | null;
        offset?: number | null;
        paged?: boolean | null;
        unpaged?: boolean | null;
    }
}
