/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const PaymentInformationType = core.serialization.enum_(["BANK_ACCOUNT", "ENCRYPTED_CREDIT_CARD", "CRYPTO", "WALLET"]);
