/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
export declare const ProviderName: core.serialization.Schema<serializers.ProviderName.Raw, PTI.ProviderName>;
export declare namespace ProviderName {
    type Raw = string;
}
