/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
export declare const TransactionStatus: core.serialization.Schema<serializers.TransactionStatus.Raw, PTI.TransactionStatus>;
export declare namespace TransactionStatus {
    type Raw = "PENDING" | "ERROR" | "MANUAL_REVIEW" | "REFUSED" | "AWAITING_PAYMENT" | "AUTHORIZED" | "ACCEPTED" | "BAD_REQUEST" | "SETTLED" | "CAPTURED" | "CHARGED_BACK" | "CHARGED_BACK_REVERSED" | "CANCELED" | "REFUNDED";
}
