/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { TransactionStatus } from "./TransactionStatus";
import { TransactionTypeEnum } from "./TransactionTypeEnum";
import { PaymentInformationType } from "./PaymentInformationType";
import { PaymentStatusDetail } from "./PaymentStatusDetail";
import { UuidLikeStrTransactionGroup } from "./UuidLikeStrTransactionGroup";
import { Total } from "./Total";
import { ActionStatus } from "./ActionStatus";
export const TransactionStatusObject = core.serialization
    .object({
    status: TransactionStatus.optional(),
    transactionType: TransactionTypeEnum.optional(),
    paymentMethod: PaymentInformationType.optional(),
    paymentStatusDetail: PaymentStatusDetail.optional(),
    amount: core.serialization.number().optional(),
    transactionGroupId: UuidLikeStrTransactionGroup.optional(),
    billingEmail: core.serialization.string().optional(),
    transactionTotal: Total.optional(),
    currency: core.serialization.string().optional(),
    additionalInfos: core.serialization
        .record(core.serialization.string(), core.serialization.unknown())
        .optional(),
})
    .extend(ActionStatus);
