/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
import { UuidLikeStrTransactionGroup } from "./UuidLikeStrTransactionGroup";
import { UuidLikeStrSubClient } from "./UuidLikeStrSubClient";
import { Total } from "./Total";
import { OneOfUserSubTypes } from "./OneOfUserSubTypes";
import { DeviceInformation } from "./DeviceInformation";
export declare const Transaction: core.serialization.ObjectSchema<serializers.Transaction.Raw, PTI.Transaction>;
export declare namespace Transaction {
    interface Raw {
        id?: string | null;
        transactionGroupId?: UuidLikeStrTransactionGroup.Raw | null;
        subClientId?: UuidLikeStrSubClient.Raw | null;
        transactionTotal?: Total.Raw | null;
        usdValue?: number | null;
        amount: number;
        date: string;
        initiator: OneOfUserSubTypes.Raw;
        ptiMeta?: Record<string, unknown> | null;
        clientMeta?: Record<string, unknown> | null;
        deviceInformation?: DeviceInformation.Raw | null;
    }
}
