/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
import { TransactionTypeEnum } from "./TransactionTypeEnum";
import { Transaction } from "./Transaction";
export declare const TransactionType: core.serialization.ObjectSchema<serializers.TransactionType.Raw, PTI.TransactionType>;
export declare namespace TransactionType {
    interface Raw extends Transaction.Raw {
        type: TransactionTypeEnum.Raw;
    }
}
