/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
import { WalletPaymentMethodWrapper } from "./WalletPaymentMethodWrapper";
import { TransactionType } from "./TransactionType";
export declare const UnstakeTransaction: core.serialization.ObjectSchema<serializers.UnstakeTransaction.Raw, PTI.UnstakeTransaction>;
export declare namespace UnstakeTransaction {
    interface Raw extends TransactionType.Raw {
        sourceMethod?: WalletPaymentMethodWrapper.Raw | null;
    }
}
