/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { OneOfUserSubTypes } from "./OneOfUserSubTypes";
import { Page } from "./Page";
export const UserPage = core.serialization
    .object({
    content: core.serialization.list(OneOfUserSubTypes).optional(),
})
    .extend(Page);
