/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const UserStatusReason = core.serialization.enum_([
    "FRAUD_SUSPICION",
    "BUSINESS_CO_OWNER",
    "COMPLIANCE_FLAG",
    "HIGH_RISK_IP",
    "INFORMATION_MISMATCH",
    "HIGH_RISK_EMAIL_DOMAIN",
    "UNUSUAL_HIGH_VELOCITY",
    "CHARGEBACK",
]);
