/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as PTI from "../../api/index";
import * as core from "../../core";
export declare const UuidLikeStrSubClient: core.serialization.Schema<serializers.UuidLikeStrSubClient.Raw, PTI.UuidLikeStrSubClient>;
export declare namespace UuidLikeStrSubClient {
    type Raw = string;
}
