/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as PTI from "../../../../../api/index";
import * as core from "../../../../../core";
import { PaymentMethodType } from "../../../../types/PaymentMethodType";
export declare const SimulatePaymentRequest: core.serialization.Schema<serializers.SimulatePaymentRequest.Raw, PTI.SimulatePaymentRequest>;
export declare namespace SimulatePaymentRequest {
    interface Raw {
        amount?: number | null;
        paymentMethodType?: PaymentMethodType.Raw | null;
    }
}
