/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as PTI from "../../../../api/index";
import * as core from "../../../../core";
import { OneOfExternalPaymentInformation } from "../../../types/OneOfExternalPaymentInformation";
export declare const Response: core.serialization.Schema<serializers.paymentInformation.getUserPaymentInformations.Response.Raw, PTI.OneOfExternalPaymentInformation[]>;
export declare namespace Response {
    type Raw = OneOfExternalPaymentInformation.Raw[];
}
