name: Release TypeScript SDK

on:
  workflow_dispatch:
    inputs:
      tag_branch:
        description: 'Tag/Branch to release'
        type: string
        required: true
      version:
        description: 'version to release'
        type: string
        required: true

env:
  GIT_KEY: ${{ secrets.CI_TOKEN }}

jobs:
  release-typescript:
    name: Release TypeScript SDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag_branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        shell: bash
        run: |
          echo -e "Checking for required packages...\n"
          if ! command -v jq &>/dev/null; then
            echo "JQ is not installed on the host. Installing now..."
            sudo apt -qq update
            sudo apt install jq -y
          else
            echo "JQ is already installed."
          fi

      - name: Set package version
        working-directory: ts
        run: |
          jq --arg ver "${{ inputs.version }}" '.version = $ver' package.json > tmp.json && mv tmp.json package.json

      - name: Commit and push updated package.json
        working-directory: ts
        run: |
          git config --global user.email "github_actions@provenancetech.io"
          git config --global user.name "Github Action"
          git add package.json
          if ! git diff --cached --quiet; then
            git commit -m "Bump TypeScript SDK version to ${{ inputs.version }}"
            git push --force origin ${{ inputs.tag_branch }}
          else
            echo "No changes to commit."
          fi

      - name: Install dependencies and publish
        working-directory: ts
        run: |
          yarn install
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ env.GIT_KEY }}
